version: '3'

services:

  webapp:

    build: . # This line needs to be indented to show that 'build' is under 'webapp'

    environment:

      - PORT=8080 # Fixed the missing space between the dash and 'PORT=8080'

  nginx:

    image: nginx:alpine

    ports:

      - "8080:80" # Corrected the typo from "8080.80" to "8080:80"

    volumes:

      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:

      - webapp # Correct indentation
